apiVersion: v1
kind: Service
metadata:
  name: nessie
  namespace: nessie
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nessie
  ports:
    - protocol: TCP
      port: 19120
      targetPort: 19120
      nodePort: 31920