apiVersion: v1
kind: Service
metadata:
  name: cnpg-cluster-rw-nodeport
  namespace: cnpg-database
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30000  # Choose a port between 30000-32767
    protocol: TCP
  selector:
    cnpg.io/cluster: cnpg-cluster
    role: primary
